import { BaseEntity }   from './baseEntity.class';
import { CoverageType }   from './enums.class';

export class Charge extends BaseEntity {
    patientClaimId!: number;
    patientPaymentId!: number;
    serviceName!:string;
    serviceNameTranslation!:string;
    serviceCode!:string;
    unitPrice!: number;
    quantity!: number;
    patientDiscount!: number;
    companyShare!: number;
    patientShare!: number;
    diagnoseName!:string;
    coverageType: CoverageType| undefined;
    netPrice!: number;
    newOverrideAmount!: number;
    isOverridden: boolean | undefined;
    releaseReason!:string;
    isReleased: boolean | undefined;
    actualNetPrice!: number;
    isSatisfied: boolean | undefined;
    satisfiedRemarks!:string;
    patientDiscountString!:string;
    companyShareString!:string;
    patientShareString!:string;
    overrideIconName!:string;
    releaseIconName!:string;
    coverageTypeIconName!:string;
    isCoverageTypeClickable: boolean | undefined;
    doctorName!:string;
    claimNo!:string;
    claimDate!:string;
    patientId!: number;
    policyId!: number;
    policyName!:string;
    isReleasedForCompany: boolean | undefined;
    isRejectedForCompany: boolean | undefined;
    rejectForCompanyIconName!:string;
    releaseForCompanyIconName!:string;
    releaseReasonForCompany!:string;
    resubmitReasonForCompany!:string;
    rejectReasonForCompany!:string;
    companyPaymentId!: number;
    insuranceCompanyNetPrice!: number;
    clinicNoteServiceId !: number;
    maxCoverageAmount !: number;
    netPriceWithoutDiscount !: number;
}