import { BaseEntity }   from './baseEntity.class';
import { CoverageType }   from './enums.class';

export class Charge extends BaseEntity {
    patientClaimId: number | undefined;
    patientPaymentId: number | undefined;
    serviceName: string | undefined;
    serviceNameTranslation: string | undefined;
    serviceCode: string | undefined;
    unitPrice: number | undefined;
    quantity: number | undefined;
    patientDiscount: number | undefined;
    companyShare: number | undefined;
    patientShare: number | undefined;
    diagnoseName: string | undefined;
    coverageType: CoverageType| undefined;
    netPrice: number | undefined;
    newOverrideAmount: number | undefined;
    isOverridden: boolean | undefined;
    releaseReason: string | undefined;
    isReleased: boolean | undefined;
    actualNetPrice: number | undefined;
    isSatisfied: boolean | undefined;
    satisfiedRemarks: string | undefined;
    patientDiscountString: string | undefined;
    companyShareString: string | undefined;
    patientShareString: string | undefined;
    overrideIconName: string | undefined;
    releaseIconName: string | undefined;
    coverageTypeIconName: string | undefined;
    isCoverageTypeClickable: boolean | undefined;
    doctorName: string | undefined;
    claimNo: string | undefined;
    claimDate: string | undefined;
    patientId: number | undefined;
    policyId: number | undefined;
    policyName: string | undefined;
    isReleasedForCompany: boolean | undefined;
    isRejectedForCompany: boolean | undefined;
    rejectForCompanyIconName: string | undefined;
    releaseForCompanyIconName: string | undefined;
    releaseReasonForCompany: string | undefined;
    resubmitReasonForCompany: string | undefined;
    rejectReasonForCompany: string | undefined;
    companyPaymentId: number | undefined;
    insuranceCompanyNetPrice: number | undefined;
    clinicNoteServiceId : number | undefined;
    maxCoverageAmount : number | undefined;
    netPriceWithoutDiscount : number | undefined;
}